insert into Publisher (publisherID, publisher_name, city, state, country) values (1, 'Springer', 'Paris', 'Paris region', 'France');
insert into Publisher (publisherID, publisher_name, city, state, country) values (2, 'Elsevier', 'London', 'London region', 'UK');
insert into Publisher (publisherID, publisher_name, city, state, country) values (3, 'Wiley', 'Rome', 'Rome region', 'Italy');
insert into Publisher (publisherID, publisher_name, city, state, country) values (4, 'Taylor & Francis', 'Berlin', 'Berlin region', 'Germany');
insert into Publisher (publisherID, publisher_name, city, state, country) values (5, 'Oxford University Press', 'Madrid', 'Madrid region', 'Spain');
insert into Publisher (publisherID, publisher_name, city, state, country) values (6, 'Cambridge University Press', 'Vienna', 'Vienna region', 'Austria');
insert into Publisher (publisherID, publisher_name, city, state, country) values (7, 'IEEE', 'Amsterdam', 'Amsterdam region', 'Netherlands');
insert into Publisher (publisherID, publisher_name, city, state, country) values (8, 'ACM', 'Prague', 'Prague region', 'Czech');
insert into Publisher (publisherID, publisher_name, city, state, country) values (9, 'Nature Publishing Group', 'Athens', 'Athens region', 'Greece');
insert into Publisher (publisherID, publisher_name, city, state, country) values (10, 'American Chemical Society', 'Stockholm', 'Stockholm region', 'Sweden');
